###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: temp1-redis

    mysql:
      image: mysql:8.0
      container_name: temp1-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root_password
        - MYSQL_DATABASE=database
        - MYSQL_USER=user
        - MYSQL_PASSWORD=user_password
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: temp1-webserver
      working_dir: /var/www
      volumes:
          - ./application:/var/www
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./logs/nginx/:/var/log/nginx          
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: temp1-php-fpm
      working_dir: /var/www
      volumes:
        - ./application:/var/www
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

